const errorHandler = async (error, req, res, next) => {
    try {

    } catch (error) {

    }
}

export default errorHandler;